# Generated by Django 3.0 on 2019-12-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_add_occupation_sexual_orientation_and_politician_models"),
    ]

    operations = [
        migrations.RenameField(model_name="politician", old_name="occupation", new_name="occupations",),
    ]
