# Generated by Django 3.0.1 on 2019-12-22 23:33

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_auto_20191218_0403"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicalGender",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("slug", models.SlugField()),
            ],
            options={"verbose_name": "Musical Gender", "verbose_name_plural": "Musical Genders",},
        ),
        migrations.AlterField(
            model_name="politician",
            name="name",
            field=models.CharField(max_length=256, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="politician",
            name="occupations",
            field=models.ManyToManyField(to="data.Occupation", verbose_name="occupations"),
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="name")),
                ("country", django_countries.fields.CountryField(max_length=2, verbose_name="country")),
                ("reference", models.URLField(blank=True, null=True, verbose_name="reference")),
                (
                    "start_birth_date",
                    models.DateField(blank=True, null=True, verbose_name="start birth date"),
                ),
                ("end_birth_date", models.DateField(blank=True, null=True, verbose_name="end birth date")),
                (
                    "start_death_date",
                    models.DateField(blank=True, null=True, verbose_name="start death date"),
                ),
                ("end_death_date", models.DateField(blank=True, null=True, verbose_name="end death date")),
                (
                    "musical_genders",
                    models.ManyToManyField(
                        blank=True, to="data.MusicalGender", verbose_name="musical gender"
                    ),
                ),
                (
                    "sexual_orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musicians",
                        to="data.SexualOrientation",
                        verbose_name="sexual orientation",
                    ),
                ),
            ],
            options={"verbose_name": "Musician", "verbose_name_plural": "Musicians",},
        ),
    ]
