# Generated by Django 3.0.2 on 2020-01-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_digitalinfluencer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalinfluencer",
            name="social_media_username",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="social media"),
        ),
    ]
