# Generated by Django 3.0.2 on 2020-01-10 03:33

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_athlet_sport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scientist",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="name")),
                ("country", django_countries.fields.CountryField(max_length=2, verbose_name="country")),
                ("reference", models.URLField(blank=True, null=True, verbose_name="reference")),
                (
                    "start_birth_date",
                    models.DateField(blank=True, null=True, verbose_name="start birth date"),
                ),
                ("end_birth_date", models.DateField(blank=True, null=True, verbose_name="end birth date")),
                (
                    "start_death_date",
                    models.DateField(blank=True, null=True, verbose_name="start death date"),
                ),
                ("end_death_date", models.DateField(blank=True, null=True, verbose_name="end death date")),
                ("occupations", models.ManyToManyField(to="data.Occupation", verbose_name="occupations")),
                (
                    "sexual_orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scientists",
                        to="data.SexualOrientation",
                        verbose_name="sexual orientation",
                    ),
                ),
            ],
            options={"verbose_name": "Scientist", "verbose_name_plural": "Scientists",},
        ),
    ]
