# Generated by Django 3.0.2 on 2020-01-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_scientist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupation", name="name", field=models.CharField(max_length=250, verbose_name="name"),
        ),
    ]
