# Generated by Django 3.0.2 on 2020-01-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_auto_20200110_0349"),
    ]

    operations = [
        migrations.AlterField(model_name="occupation", name="slug", field=models.SlugField(max_length=250),),
    ]
