# Generated by Django 3.0.2 on 2020-01-12 23:33

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_auto_20200110_0410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="countries",
            field=django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name="country"),
        ),
    ]
