# Generated by Django 3.0.2 on 2020-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0012_auto_20200112_2333"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="name")),
                ("slug", models.SlugField()),
            ],
            options={"verbose_name": "Social Media", "verbose_name_plural": "Social Medias",},
        ),
        migrations.AddField(
            model_name="digitalinfluencer",
            name="main_social_medias",
            field=models.ManyToManyField(
                blank=True, to="data.SocialMedia", verbose_name="main social medias"
            ),
        ),
    ]
