# Generated by Django 3.0.7 on 2020-06-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0014_auto_20200608_0217"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="athlet", options={"verbose_name": "Athlet", "verbose_name_plural": "Athletes"},
        ),
    ]
