# Generated by Django 3.0.7 on 2020-06-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_auto_20200617_0038"),
    ]

    operations = [
        migrations.RenameModel(old_name="MovieGender", new_name="MovieGenre",),
        migrations.RenameModel(old_name="MusicalGender", new_name="MusicalGenre",),
        migrations.AlterModelOptions(
            name="moviegenre",
            options={
                "ordering": ("slug",),
                "verbose_name": "Movie Genre",
                "verbose_name_plural": "Movie Genres",
            },
        ),
        migrations.AlterModelOptions(
            name="musicalgenre",
            options={
                "ordering": ("slug",),
                "verbose_name": "Musical Genre",
                "verbose_name_plural": "Musical Genres",
            },
        ),
        migrations.RemoveField(model_name="movie", name="genders",),
        migrations.RemoveField(model_name="musician", name="musical_genders",),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="data.MovieGenre", verbose_name="movie genres"
            ),
        ),
        migrations.AddField(
            model_name="musician",
            name="musical_genres",
            field=models.ManyToManyField(blank=True, to="data.MusicalGenre", verbose_name="musical genre"),
        ),
    ]
