# Generated by Django 3.0.3 on 2020-03-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=250)),
                ("reason", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "Invite", "verbose_name_plural": "Invites",},
        ),
    ]
