# Generated by Django 3.0.3 on 2020-03-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
