# Generated by Django 3.0.4 on 2020-04-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_invite_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSuggestion",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.TextField()),
            ],
        ),
    ]
