# Generated by Django 3.0.7 on 2020-06-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0003_datasuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasuggestion", name="reject_reason", field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datasuggestion",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
